version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: prediction
      POSTGRES_PASSWORD: prediction
      POSTGRES_DB: prediction
    ports:
      - "5432:5432"